bash: SBATCH: command not found
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1544176307774/work/aten/src/THC/THCGeneral.cpp line=51 error=38 : no CUDA-capable device is detected
Namespace(batchSize=64, beta1=0.5, cuda=True, dataroot='/home/s1832582/zappos-shoes', dataset='folder', imageSize=64, lr=0.0002, manualSeed=None, ndf=64, netD='', netG='', ngf=64, ngpu=1, niter=25, nz=100, outf='/home/s1832582/', workers=2)
Random Seed:  3657
Traceback (most recent call last):
  File "dcgan.py", line 152, in <module>
    netG = Generator(ngpu).to(device)
  File "/home/s1832582/miniconda3/envs/mlp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 381, in to
    return self._apply(convert)
  File "/home/s1832582/miniconda3/envs/mlp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/home/s1832582/miniconda3/envs/mlp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/home/s1832582/miniconda3/envs/mlp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    param.data = fn(param.data)
  File "/home/s1832582/miniconda3/envs/mlp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 379, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "/home/s1832582/miniconda3/envs/mlp/lib/python3.7/site-packages/torch/cuda/__init__.py", line 162, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /opt/conda/conda-bld/pytorch_1544176307774/work/aten/src/THC/THCGeneral.cpp:51
